### ISSUE TITLE
Console serveFile/error/notFount exception although the page is displayed in the browser

### ISSUE THREAD

**Issue by silviubogan** [IonicaBizau/statique#51]
```js
var Statique = require("statique"),
    Http = require("http");

var server = new Statique({
    root: __dirname + "/public",
    cache: 36000
}).setRoutes({
    "/": "/index.html"
}).setErrors({
    404: __dirname + "/http_errors/404.html",
    500: __dirname + "/http_errors/500.html"
});

Http.createServer(server.serve.bind(server)).listen(9000, function (err) {
    // Output
    console.log("Listening on port 9000.");
});
```
After a first request to the `/` path, the browser displays the contents of `index.html` but throws an exception in the terminal and quits:

```
Launch configuration created based on 'package.json'.
Debugging with inspector protocol because Node.js v8.6.0 was detected.
node --inspect-brk=32081 server.js 
Debugger listening on ws://127.0.0.1:32081/c045aa49-51f3-4db1-917b-feb48c577664
Debugger attached.
Listening on port 9000.
RangeError: Maximum call stack size exceeded
    at Statique.serveFile (/home/silviu/git/motorola-v3-simulator/node_modules/statique/lib/index.js:410:41)
    at Statique.error (/home/silviu/git/motorola-v3-simulator/node_modules/statique/lib/index.js:599:21)
    at Statique.notFound (/home/silviu/git/motorola-v3-simulator/node_modules/statique/lib/index.js:378:17)
    at Statique.serveFile (/home/silviu/git/motorola-v3-simulator/node_modules/statique/lib/index.js:431:14)
    at Statique.error (/home/silviu/git/motorola-v3-simulator/node_modules/statique/lib/index.js:599:21)
    at Statique.notFound (/home/silviu/git/motorola-v3-simulator/node_modules/statique/lib/index.js:378:17)
    at Statique.serveFile (/home/silviu/git/motorola-v3-simulator/node_modules/statique/lib/index.js:431:14)
    at Statique.error (/home/silviu/git/motorola-v3-simulator/node_modules/statique/lib/index.js:599:21)
    at Statique.notFound (/home/silviu/git/motorola-v3-simulator/node_modules/statique/lib/index.js:378:17)
    at Statique.serveFile (/home/silviu/git/motorola-v3-simulator/node_modules/statique/lib/index.js:431:14)
```

I attached my entire project in a `.zip` archive: [motorola-v3-simulator-07.10.2017-1138.zip](https://github.com/IonicaBizau/statique/files/1364400/motorola-v3-simulator-07.10.2017-1138.zip).

I am currently working to understand this bug and solve it.

**Comment by silviubogan** [comment]
I think I solved this issue by adding a detail to a documentation comment: #52.
